name: Name from the download file
on: workflow_dispatch
jobs:
  job_1:
    name: download
    runs-on: ubuntu-latest
    steps:
      - uses: actions/upload-download@v3
        with:
          name: remark-lint-report
      - run: | 
           echo "hello"
           cat remark-lint-report.json
