name: Name from the download file
on: workflow_dispatch
jobs:
  job_0:
    name: upload
    runs-on: ubuntu-latest
    steps:
      - run: echo "Dans l'artifact" > file.txt
      - uses: actions/upload-artifact@v3
        with:
          name: file
          path: file.txt
        
    
  job_1:
    name: download
    runs-on: ubuntu-latest
    needs: job_0
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: file
      - run: | 
           echo "hello"
           cat file.txt
